language: node_js

node_js: 10.16.3

branches:
  only:
    - master

env:
  matrix:
    - TASK=nojsx
    - TASK=jest NODE_VERSION=v8.15.0 YARN_VERSION=1.13.0
    - TASK=eslint NODE_VERSION=v8.15.0
    - TASK=build

install:
  - if [ $TASK == jest ];
      then npm i -g yarn@1.3.2;
      yarn install;

    elif [ $TASK = eslint ]; then
      npm i eslint
        eslint-plugin-react-hooks
        eslint-plugin-promise
        eslint-plugin-standard
        eslint-config-standard
        eslint-config-standard-react
        eslint-config-standard-jsx
        eslint-plugin-react
        eslint-plugin-babel
        babel-eslint
        eslint-plugin-import
        eslint-plugin-node;

    elif [ $TASK == build ]; then npm i -g yarn@1.3.2; yarn install; fi

script: ./.travis.script.sh

after_script:
  - if [ $TASK == jest ]; then yarn codecov; fi


notifications:
  email: false
